[metadata]
name = vi-learn-docker
version =  0.0.1
author = vi
author_email = inbox@it-thematic.ru
classifiers =
    Framework :: Django
    Framework :: DjangoRESTFramework
    Programming Language :: Python :: 3.12
[flake8]
extend_exclude =
          env
          venv
          dist
          tests/fixtures/**
          tests/**/snapshots/**
          **/__init__.py
max-line-length = 120
max-complexity = 9
inline-quotes = "

# flake8-docstrings
docstring-convention = numpy
ignore = D100, D101, D102, D103, D104, D105, D106, D401

[autoflake]
check = true

[tool:pytest]
testpaths =
    tests
filterwarnings =
    ignore::FutureWarning
    ignore::DeprecationWarning
# PYTEST-DJANGO
django_debug_mode = true
DJANGO_SETTINGS_MODULE = config.settings
; addopts = --cov --cov-report html

[semantic_release]
version_pattern = VERSION:(\d+\.\d+\.\d+)
version_source = tag

tag_commit = true

[isort]
py_version = 38
skip = __pycache__,env,tests
line_length = 120
